services: 
  web: 
    build:  .
    ports: 
      - "80:80" 
    volumes: 
      - .:/var/www/html 
    depends_on: 
      - db 
  db: 
    image: mysql:5.7 
    environment: 
      MYSQL_ROOT_PASSWORD: exemple
      MYSQL_DATABASE: mon_projet_php 
    volumes: 
      - ./docker/mysql/mon_projet_php:/var/lib/mysql 
  adminer: 
    image: adminer 
    restart: always 
    ports: 
      - 8081:8080